[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
spinx_contract = "6W1JspEray9RAnC7oVFa6fHwcSdt9XkWyd7MShFkvGKw"

[programs.mainnet]
spinx_contract = "6W1JspEray9RAnC7oVFa6fHwcSdt9XkWyd7MShFkvGKw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/spinx_id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
